apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: wobds7mw0-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/wobds7mw0-java-springboot-gitops